/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seie.crud;

import java.awt.event.KeyEvent;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author HelpDesk-Seie
 */
public class Validacao extends javax.swing.JFrame {

    /**
     * Creates new form Validacao
     */
    public Validacao() {
        initComponents();
    }

    public Boolean valicaoDouble(KeyEvent e, JTextField tf) {
        boolean valido = true;
        String s = String.valueOf(e.getKeyChar());
        if (tf.getText().length() == 0) {
            if (!s.matches("[0-9]")) {
                e.consume();
                getToolkit().beep();
            }
        } else if (!s.matches("[0-9.]")) {
            e.consume();
            getToolkit().beep();
        }

        return valido;
    }
    
    public Boolean valicaoNome(KeyEvent e, JTextField tf) {
        boolean valido = true;
        String s = String.valueOf(e.getKeyChar());
        if (tf.getText().length() == 0) {
            if (!s.matches("[A-Za-z]")) {
                e.consume();
                getToolkit().beep();
            }
        } else if (!s.matches("[A-Za-z ]")) {
            e.consume();
            getToolkit().beep();
        }

        return valido;
    }
    
    public Boolean valicaoUtilizador(KeyEvent e, JTextField tf) {
        boolean valido = true;
        String s = String.valueOf(e.getKeyChar());
        if (tf.getText().length() == 0) {
            if (!s.matches("[A-Za-z]")) {
                e.consume();
                getToolkit().beep();
            }
        } else if (!s.matches("[A-Za-z_0-9 ]")) {
            e.consume();
            getToolkit().beep();
        }

        return valido;
    }
    
    public Boolean valicaoUtilizador(KeyEvent e, JTextArea tf) {
        boolean valido = true;
        String s = String.valueOf(e.getKeyChar());
        if (tf.getText().length() == 0) {
            if (!s.matches("[A-Za-z]")) {
                e.consume();
                getToolkit().beep();
            }
        } else if (!s.matches("[A-Za-z_0-9.áçõãéíóú ]")) {
            e.consume();
            getToolkit().beep();
        }

        return valido;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Validacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Validacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Validacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Validacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Validacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
