/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seie.visao;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import seie.crud.CaixasCRUD;
import seie.crud.ContaCRUD;
import seie.modelo.Agencia;
import seie.modelo.Caixa;
import seie.modelo.Conta;
import seie.modelo.Movimentos;

/**
 *
 * @author HelpDesk-Seie
 */
public class MenuCaixa extends javax.swing.JFrame {

    /**
     * Creates new form MenuCliente
     */
    Caixa modCaixa = new Caixa();
    Agencia modAgencia = new Agencia();
    CaixasCRUD crudCaixa = new CaixasCRUD();
    ContaCRUD crudConta = new ContaCRUD();
    List<Conta> contas = new ArrayList<>();
    List<Caixa> caixas = new ArrayList<>();

    public MenuCaixa() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    public MenuCaixa(Agencia agencia, Caixa caixa) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        modCaixa = caixa;
        modAgencia = agencia;

        this.caixas = crudCaixa.caixas();
        this.contas = crudConta.contas();

        informacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        btnSugestoes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pnlEsq = new javax.swing.JPanel();
        btnLevantamento = new javax.swing.JButton();
        btnImprimirExtracto = new javax.swing.JButton();
        btnDepositos = new javax.swing.JButton();
        btnAberturaDeConta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbBalcaoAtNr = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbNomeCaixa = new javax.swing.JLabel();
        lbHoras = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Outras Opções", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnSair.setBackground(new java.awt.Color(255, 255, 255));
        btnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("Sair do Sistema");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSairMouseExited(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSugestoes.setBackground(new java.awt.Color(255, 255, 255));
        btnSugestoes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSugestoes.setText("Sugestões");
        btnSugestoes.setToolTipText("Sair do Sistema");
        btnSugestoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSugestoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSugestoesMouseExited(evt);
            }
        });
        btnSugestoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSugestoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(590, Short.MAX_VALUE)
                .addComponent(btnSugestoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSugestoes, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlPrincipal.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Principais Operações", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        btnLevantamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLevantamento.setForeground(new java.awt.Color(0, 0, 102));
        btnLevantamento.setText("Levantamento");
        btnLevantamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevantamentoActionPerformed(evt);
            }
        });

        btnImprimirExtracto.setBackground(new java.awt.Color(255, 255, 255));
        btnImprimirExtracto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImprimirExtracto.setForeground(new java.awt.Color(0, 0, 102));
        btnImprimirExtracto.setText("Imprimir Extracto");
        btnImprimirExtracto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirExtractoActionPerformed(evt);
            }
        });

        btnDepositos.setBackground(new java.awt.Color(204, 204, 255));
        btnDepositos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDepositos.setForeground(new java.awt.Color(0, 0, 102));
        btnDepositos.setText("Depósitos");
        btnDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositosActionPerformed(evt);
            }
        });

        btnAberturaDeConta.setBackground(new java.awt.Color(255, 255, 255));
        btnAberturaDeConta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAberturaDeConta.setForeground(new java.awt.Color(0, 0, 102));
        btnAberturaDeConta.setText("Abertura de Conta");
        btnAberturaDeConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAberturaDeContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEsqLayout = new javax.swing.GroupLayout(pnlEsq);
        pnlEsq.setLayout(pnlEsqLayout);
        pnlEsqLayout.setHorizontalGroup(
            pnlEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEsqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnImprimirExtracto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                        .addComponent(btnDepositos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLevantamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnAberturaDeConta, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        pnlEsqLayout.setVerticalGroup(
            pnlEsqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEsqLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnLevantamento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepositos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimirExtracto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAberturaDeConta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pnlEsq);

        lbBalcaoAtNr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbBalcaoAtNr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbBalcaoAtNr.setText("Balacão do Atendimento Nr.:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Banco UniBancos");

        lbNomeCaixa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNomeCaixa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNomeCaixa.setText("Maria Madalena");

        lbHoras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbHoras.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbHoras.setText("Horas:");

        lbData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbData.setText("Data:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBalcaoAtNr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomeCaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBalcaoAtNr, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNomeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(lbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3);

        pnlPrincipal.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseEntered
        btnSair.setBackground(Color.red);
    }//GEN-LAST:event_btnSairMouseEntered

    private void btnSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseExited
        btnSair.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnSairMouseExited

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSugestoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSugestoesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSugestoesMouseEntered

    private void btnSugestoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSugestoesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSugestoesMouseExited

    private void btnSugestoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSugestoesActionPerformed
        
        System.out.println("\n\n"+crudCaixa.toString(modAgencia));
        
    }//GEN-LAST:event_btnSugestoesActionPerformed

    private void btnLevantamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevantamentoActionPerformed
        String nrDaConta = JOptionPane.showInputDialog("Digite o Número da conta");
        Conta conta = null; int i = 0;
        this.contas = crudConta.contas();
        if (nrDaConta.matches("[0-9]{1,}")) {
            for (Conta c : contas) {
                if (c.getNumero() == Long.parseLong(nrDaConta)) {
                    conta = c;
                    break;
                }
                i++;
            }
        } else {
            JOptionPane.showMessageDialog(null, "O número da conta digitada não é válido!");
        }

        if (conta != null) {
            new TelaLevantamentos(this.modAgencia,conta.getCliente(),this.modCaixa,conta,this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Não existe Cliente com esse número de conta");
        }
    }//GEN-LAST:event_btnLevantamentoActionPerformed

    private void btnDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositosActionPerformed
        String nrDaConta = JOptionPane.showInputDialog("Digite o Número da conta");
        Conta modConta = null; int i = 0;
        if (nrDaConta.matches("[0-9]{1,}")) {
            for (Conta c : contas) {
                if (c.getNumero() == Long.parseLong(nrDaConta)) {
                    modConta = c;
                    break;
                }
                i++;
            }
        } else {
            JOptionPane.showMessageDialog(null, "O número da conta digitada não é válido!");
        }

        if (modConta != null) {
            new TelaDepositos(this.modAgencia,modConta.getCliente(),this.modCaixa,modConta,this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Não existe Cliente com esse número de conta");
        }


    }//GEN-LAST:event_btnDepositosActionPerformed

    private void btnImprimirExtractoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirExtractoActionPerformed
        String nrDaConta = JOptionPane.showInputDialog(this, "Digite o número da conta do Cliente a se visualizar o seu Extracto", "Conta do Cliente", JOptionPane.QUESTION_MESSAGE);
        Conta modConta = null; int i = 0;
        this.contas = crudConta.contas();
        if (nrDaConta.matches("[0-9]{1,}")) {
            for (Conta c : contas) {
                if (c.getNumero() == Long.parseLong(nrDaConta)) {
                    modConta = c;
                    break;
                }
                i++;
            }
        } else {
            JOptionPane.showMessageDialog(null, "O número da conta digitada não é válido!");
        }

        if (modConta != null) {
            new TelaExtracto(this, true,modConta).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Não existe Cliente com esse número de conta");
        }


        
    }//GEN-LAST:event_btnImprimirExtractoActionPerformed

    private void btnAberturaDeContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAberturaDeContaActionPerformed

        new CadastroDeCliente(this.modAgencia, this, true).setVisible(true);
        this.contas = crudConta.contas();
    }//GEN-LAST:event_btnAberturaDeContaActionPerformed

    public void informacao() {

        lbBalcaoAtNr.setText(lbBalcaoAtNr.getText() + " " + this.modCaixa.getBalcao());
        lbNomeCaixa.setText(this.modCaixa.getNome());

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        lbData.setText(sdf.format(new Date()));

        Timer t = new Timer();
        t.scheduleAtFixedRate(new relogio(), 0, 1000);
    }

    public class relogio extends TimerTask {

        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");

        public void run() {
            lbHoras.setText(sdf.format(new Date()));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAberturaDeConta;
    private javax.swing.JButton btnDepositos;
    private javax.swing.JButton btnImprimirExtracto;
    private javax.swing.JButton btnLevantamento;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSugestoes;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbBalcaoAtNr;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbHoras;
    private javax.swing.JLabel lbNomeCaixa;
    private javax.swing.JPanel pnlEsq;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
