/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seie.visao;

import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.Time;
import java.util.Date;
import javax.swing.JOptionPane;
import seie.crud.Banco;
import seie.crud.CaixasCRUD;
import seie.crud.Validacao;
import seie.modelo.Agencia;
import seie.modelo.Caixa;
import seie.modelo.Cliente;
import seie.modelo.Conta;
import seie.modelo.Movimentos;

/**
 *
 * @author HelpDesk-Seie
 */
public class TelaDepositos extends javax.swing.JDialog {

    /**
     * Creates new form Levantamentos
     */
    String strValorDes = "Valor a Depositar";
    Validacao v = new Validacao();
    Conta modConta = new Conta();
    Agencia modAgencia = new Agencia();
    Cliente modCliente = new Cliente();
    Caixa modCaixa = new Caixa();
    Movimentos mov = new Movimentos();
    CaixasCRUD crudCaixa = new CaixasCRUD();
    Banco banco = new Banco();

    public TelaDepositos(Agencia agencia,Cliente cliente, Caixa caixa,Conta conta,Frame frame, boolean modal) {
        super(frame, modal);
        initComponents();
        
        this.modCaixa = caixa;
        this.modConta = conta;
        this.modAgencia = agencia;
        this.modCliente = cliente;
        tfNumeroDaConta.setText(""+conta.getNumero());
        tfNomeCliente.setText(""+conta.getCliente().getNome());
    }
    

    public TelaDepositos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        tfValorADepositar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfNumeroDaConta = new javax.swing.JTextField();
        btnDepositar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tfNomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Depósitos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tfValorADepositar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfValorADepositar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfValorADepositar.setText("Valor a Depositar");
        tfValorADepositar.setToolTipText("Valor a Sacar");
        tfValorADepositar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfValorADepositarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfValorADepositarFocusLost(evt);
            }
        });
        tfValorADepositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfValorADepositarMouseEntered(evt);
            }
        });
        tfValorADepositar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfValorADepositarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfValorADepositarKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Número da Conta.:");

        tfNumeroDaConta.setEditable(false);
        tfNumeroDaConta.setBackground(new java.awt.Color(204, 204, 204));
        tfNumeroDaConta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfNumeroDaConta.setForeground(new java.awt.Color(0, 0, 102));
        tfNumeroDaConta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumeroDaConta.setText("12345");
        tfNumeroDaConta.setToolTipText("Saldo Disponivel");

        btnDepositar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tfNomeCliente.setBackground(new java.awt.Color(204, 204, 204));
        tfNomeCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfNomeCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNomeCliente.setText("Nome do Cliente");
        tfNomeCliente.setToolTipText("Saldo Disponivel");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Proprietário:");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfValorADepositar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(tfNumeroDaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tfValorADepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDepositar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(379, 348));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfValorADepositarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfValorADepositarMouseEntered

    }//GEN-LAST:event_tfValorADepositarMouseEntered

    private void tfValorADepositarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorADepositarFocusGained
        if (tfValorADepositar.getText().equals(strValorDes)) {
            tfValorADepositar.setText("");
        }
    }//GEN-LAST:event_tfValorADepositarFocusGained

    private void tfValorADepositarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorADepositarFocusLost
        if(tfValorADepositar.getText().length() == 0){
            tfValorADepositar.setText(strValorDes);
        }
    }//GEN-LAST:event_tfValorADepositarFocusLost

    private void tfValorADepositarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorADepositarKeyTyped
        v.valicaoDouble(evt, tfValorADepositar);
    }//GEN-LAST:event_tfValorADepositarKeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        
        depositar();
        
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void tfValorADepositarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorADepositarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            depositar();
        }
    }//GEN-LAST:event_tfValorADepositarKeyPressed

    public void depositar(){
        String saldoS = tfValorADepositar.getText();
       try{ 
        if(tfValorADepositar.getText().length() > 0){
            
            this.modConta.setSaldo(this.modConta.getSaldo()+Double.parseDouble(saldoS));
            mov.setCaixa(this.modCaixa);
            mov.setAgencia(this.modAgencia);
            mov.setCliente(this.modCliente);
            mov.setConta(this.modConta);
            mov.setValorEntrada(Double.parseDouble(saldoS));
            mov.setValorActual(modConta.getSaldo());
            mov.setData(new Date());
            mov.setHora(new Date());
            mov.setTipo("Depósito");
            
            if(banco.deposito(modConta,mov)){
                modCaixa.setQtdDepositos();
                crudCaixa.alterar(modCaixa);
                System.out.println("Depositado com sucesso...");
                dispose();
            } else {
                System.out.println("Erro no Depositado com sucesso...");
            }
            
        }
       }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Digite um Valor Válido");
       }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDepositos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDepositos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDepositos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDepositos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDepositos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField tfNomeCliente;
    private javax.swing.JTextField tfNumeroDaConta;
    private javax.swing.JTextField tfValorADepositar;
    // End of variables declaration//GEN-END:variables
}
