/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seie.visao;

import java.awt.Frame;
import seie.crud.Validacao;

/**
 *
 * @author HelpDesk-Seie
 */
public class TelaTransferencias extends javax.swing.JDialog {

    /**
     * Creates new form Levantamentos
     */
    String strValorDes = "Valor a Transferir";
    Validacao v = new Validacao();

    public TelaTransferencias(Frame frame, boolean modal) {
        super(frame, modal);
        initComponents();
    }

    public TelaTransferencias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        tfValorDesejado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfSaldoDisponivel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Transferencias", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tfValorDesejado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfValorDesejado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfValorDesejado.setText("Valor a Transferir");
        tfValorDesejado.setToolTipText("Valor a Sacar");
        tfValorDesejado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfValorDesejadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfValorDesejadoFocusLost(evt);
            }
        });
        tfValorDesejado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfValorDesejadoMouseEntered(evt);
            }
        });
        tfValorDesejado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfValorDesejadoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Conta a Receber.:");

        tfSaldoDisponivel.setBackground(new java.awt.Color(255, 255, 51));
        tfSaldoDisponivel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfSaldoDisponivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSaldoDisponivel.setText("12345");
        tfSaldoDisponivel.setToolTipText("Saldo Disponivel");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Transferir");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Cancelar");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                            .addComponent(tfValorDesejado, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65))
                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62)
                            .addComponent(jButton2)
                            .addContainerGap()))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSaldoDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(tfSaldoDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(tfValorDesejado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(100, 100, 100))
        );

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(357, 251));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfValorDesejadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfValorDesejadoMouseEntered

    }//GEN-LAST:event_tfValorDesejadoMouseEntered

    private void tfValorDesejadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorDesejadoFocusGained
        if (tfValorDesejado.getText().equals(strValorDes)) {
            tfValorDesejado.setText("");
        }
    }//GEN-LAST:event_tfValorDesejadoFocusGained

    private void tfValorDesejadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorDesejadoFocusLost
        if(tfValorDesejado.getText().length() == 0){
            tfValorDesejado.setText(strValorDes);
        }
    }//GEN-LAST:event_tfValorDesejadoFocusLost

    private void tfValorDesejadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorDesejadoKeyTyped
        v.valicaoDouble(evt, tfValorDesejado);
    }//GEN-LAST:event_tfValorDesejadoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTransferencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField tfSaldoDisponivel;
    private javax.swing.JTextField tfValorDesejado;
    // End of variables declaration//GEN-END:variables
}
