/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seie.visao;

import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.Time;
import java.util.Date;
import seie.crud.Banco;
import seie.crud.CaixasCRUD;
import seie.crud.Validacao;
import seie.modelo.Agencia;
import seie.modelo.Caixa;
import seie.modelo.Cliente;
import seie.modelo.Conta;
import seie.modelo.Movimentos;

/**
 *
 * @author HelpDesk-Seie
 */
public class TelaLevantamentos extends javax.swing.JDialog {

    /**
     * Creates new form Levantamentos
     */
    String strValorDes = "Digite aqui o Valor que deseja Sacar";
    Validacao v = new Validacao();
    Conta modConta = new Conta();
    CaixasCRUD crudCaixa = new CaixasCRUD();
    Banco banco = new Banco();
    Agencia modAgencia = new Agencia();
    Cliente modCliente = new Cliente();
    Caixa modCaixa = new Caixa();
    Movimentos mov = new Movimentos();

    public TelaLevantamentos(Agencia agencia,Cliente cliente, Caixa caixa,Conta conta, Frame frame, boolean modal) {
        super(frame, modal);
        initComponents();

        tfSaldoDisponivel.setText("" + conta.getSaldo());
        tfProprietario.setText("" + conta.getCliente().getNome());
        tfNumerodaConta.setText("" + conta.getNumero());

        this.modCaixa = caixa;
        this.modConta = conta;
        this.modAgencia = agencia;
        this.modCliente = cliente;

    }
    
    public TelaLevantamentos(Cliente cliente,Frame frame, boolean modal) {
        super(frame, modal);
        initComponents();

        tfSaldoDisponivel.setText("" + cliente.getContas().get(0).getSaldo());
        tfProprietario.setText("" + cliente.getNome());
        tfNumerodaConta.setText("" + cliente.getContas().get(0).getNumero());

        this.modCliente = cliente;

    }

    public TelaLevantamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        tfValorDesejado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfSaldoDisponivel = new javax.swing.JTextField();
        btnLevantar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tfNumerodaConta = new javax.swing.JTextField();
        tfProprietario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Levantamentos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tfValorDesejado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfValorDesejado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfValorDesejado.setText("Digite aqui o Valor que deseja Sacar");
        tfValorDesejado.setToolTipText("Valor a Sacar");
        tfValorDesejado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfValorDesejadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfValorDesejadoFocusLost(evt);
            }
        });
        tfValorDesejado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfValorDesejadoMouseEntered(evt);
            }
        });
        tfValorDesejado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfValorDesejadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfValorDesejadoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Saldo Disponível");

        tfSaldoDisponivel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tfSaldoDisponivel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSaldoDisponivel.setText("24567.09");
        tfSaldoDisponivel.setToolTipText("Saldo Disponivel");

        btnLevantar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLevantar.setText("Sacar");
        btnLevantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevantarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tfNumerodaConta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfNumerodaConta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumerodaConta.setText("Número da Conta");
        tfNumerodaConta.setToolTipText("Número da Conta");
        tfNumerodaConta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNumerodaContaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNumerodaContaFocusLost(evt);
            }
        });
        tfNumerodaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNumerodaContaMouseEntered(evt);
            }
        });
        tfNumerodaConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNumerodaContaKeyTyped(evt);
            }
        });

        tfProprietario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfProprietario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfProprietario.setText("Digite aqui o Valor que deseja Sacar");
        tfProprietario.setToolTipText("Proprietario da conta");
        tfProprietario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfProprietarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfProprietarioFocusLost(evt);
            }
        });
        tfProprietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfProprietarioMouseEntered(evt);
            }
        });
        tfProprietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfProprietarioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlPrincipalLayout.createSequentialGroup()
                            .addComponent(btnLevantar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnCancelar))
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfValorDesejado)
                            .addComponent(tfSaldoDisponivel)
                            .addComponent(tfNumerodaConta, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(tfProprietario))))
                .addGap(121, 121, 121))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(tfSaldoDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(tfNumerodaConta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfProprietario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(tfValorDesejado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLevantar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(470, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfValorDesejadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfValorDesejadoMouseEntered

    }//GEN-LAST:event_tfValorDesejadoMouseEntered

    private void tfValorDesejadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorDesejadoFocusGained
        if (tfValorDesejado.getText().equals(strValorDes)) {
            tfValorDesejado.setText("");
        }
    }//GEN-LAST:event_tfValorDesejadoFocusGained

    private void tfValorDesejadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorDesejadoFocusLost
        if (tfValorDesejado.getText().length() == 0) {
            tfValorDesejado.setText(strValorDes);
        }
    }//GEN-LAST:event_tfValorDesejadoFocusLost

    private void tfValorDesejadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorDesejadoKeyTyped
        v.valicaoDouble(evt, tfValorDesejado);
    }//GEN-LAST:event_tfValorDesejadoKeyTyped

    private void tfNumerodaContaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumerodaContaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumerodaContaFocusGained

    private void tfNumerodaContaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNumerodaContaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumerodaContaFocusLost

    private void tfNumerodaContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNumerodaContaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumerodaContaMouseEntered

    private void tfNumerodaContaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNumerodaContaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumerodaContaKeyTyped

    private void tfProprietarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfProprietarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProprietarioFocusGained

    private void tfProprietarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfProprietarioFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProprietarioFocusLost

    private void tfProprietarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfProprietarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProprietarioMouseEntered

    private void tfProprietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfProprietarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProprietarioKeyTyped

    private void tfValorDesejadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorDesejadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            levantar();
        }
    }//GEN-LAST:event_tfValorDesejadoKeyPressed

    private void btnLevantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevantarActionPerformed
        levantar();
    }//GEN-LAST:event_btnLevantarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void levantar() {
        String saldoDesejadoString = tfValorDesejado.getText();

        if (tfValorDesejado.getText().length() > 0) {
            double saldoDesejDouble = Double.parseDouble(saldoDesejadoString);
            if (this.modConta.getSaldo() > saldoDesejDouble) {
                double saldoFinal = this.modConta.getSaldo() - saldoDesejDouble;
                this.modConta.setSaldo(saldoFinal);

                mov.setCaixa(this.modCaixa);
                mov.setAgencia(this.modAgencia);
                mov.setCliente(this.modCliente);
                mov.setConta(this.modConta);
                mov.setValorSaida(Double.parseDouble(saldoDesejadoString));
                mov.setValorActual(saldoFinal);
                mov.setData(new Date());
                mov.setHora(new Date());
                mov.setTipo("Levantamento");

                if (banco.saque(this.modConta,mov)) {
                    System.out.println("Levantando com sucesso...");
                    dispose();
                }
            } else {
                System.out.println("Erro no Levantamento");
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLevantamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLevantamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLevantamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLevantamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLevantamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLevantar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTextField tfNumerodaConta;
    private javax.swing.JTextField tfProprietario;
    private javax.swing.JTextField tfSaldoDisponivel;
    private javax.swing.JTextField tfValorDesejado;
    // End of variables declaration//GEN-END:variables
}
